export const SELECT_PROFILE = "SELECT_PROFILE";
export const ADD_PROFILE = "ADD_PROFILE";
export const DELETE_PROFILE = "DELETE_PROFILE";
export const RENAME_PROFILE = "RENAME_PROFILE";
export const MOVE_PROFILE_UP = "MOVE_PROFILE_UP";
export const MOVE_PROFILE_DOWN = "MOVE_PROFILE_DOWN";
